# pnnx model stat
# model inputshape = [1,3,?,?]f32,[1,1152,?,?]f32
# FLOPS = 0
# memory OPS = 2.048K

import os
import numpy as np
import tempfile, zipfile
import torch
import torch.nn as nn
import torch.nn.functional as F
try:
    import torchvision
    import torchaudio
except:
    pass

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()

        self.patch_embedding = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=3, kernel_size=(16,16), out_channels=1152, padding=(0,0), padding_mode='zeros', stride=(16,16))
        self.layers_0_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_0 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_0_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_0_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_0_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_1_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_1 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_1_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_1_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_1_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_2_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_2 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_2_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_2_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_2_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_3_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_3 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_3_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_3_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_3_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_4_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_4 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_4_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_4_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_4_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_5_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_5 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_5_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_5_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_5_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_6_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_6 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_6_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_6_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_6_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_7_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_7 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_7_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_7_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_7_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_8_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_8 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_8_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_8_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_8_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_9_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_9 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_9_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_9_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_9_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_10_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_10 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_10_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_10_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_10_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_11_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_11 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_11_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_11_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_11_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_12_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_12 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_12_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_12_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_12_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_13_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_13 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_13_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_13_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_13_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_14_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_14 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_14_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_14_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_14_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_15_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_15 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_15_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_15_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_15_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_16_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_16 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_16_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_16_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_16_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_17_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_17 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_17_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_17_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_17_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_18_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_18 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_18_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_18_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_18_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_19_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_19 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_19_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_19_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_19_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_20_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_20 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_20_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_20_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_20_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_21_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_21 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_21_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_21_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_21_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_22_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_22 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_22_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_22_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_22_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_23_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_23 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_23_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_23_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_23_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_24_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_24 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_24_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_24_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_24_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_25_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_25 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_25_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_25_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_25_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.layers_26_input_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.attention_26 = nn.MultiheadAttention(add_bias_kv=False, add_zero_attn=False, batch_first=True, bias=True, embed_dim=1152, kdim=1152, num_heads=16, vdim=1152)
        self.layers_26_post_attention_layernorm = nn.LayerNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.layers_26_mlp_dense_h_to_4h = nn.Linear(bias=True, in_features=1152, out_features=4304)
        self.layers_26_mlp_dense_4h_to_h = nn.Linear(bias=True, in_features=4304, out_features=1152)
        self.rmsnorm_0 = nn.RMSNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1152,))
        self.perceive_proj_0 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=1152, kernel_size=(2,2), out_channels=2304, padding=(0,0), padding_mode='zeros', stride=(2,2))
        self.perceive_proj_1 = nn.GELU()
        self.perceive_proj_2 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=2304, kernel_size=(1,1), out_channels=4608, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.perceive_mlp = nn.Linear(bias=True, in_features=4608, out_features=1024)
        self.rmsnorm_1 = nn.RMSNorm(elementwise_affine=True, eps=1.000000e-5, normalized_shape=(1024,))

        archive = zipfile.ZipFile('D:\MySystem\share\SummerNcnn\pnnx\ncnn_ocr\scripts\ncnn\vision_encoder.pnnx.bin', 'r')
        self.patch_embedding.bias = self.load_pnnx_bin_as_parameter(archive, 'patch_embedding.bias', (1152), 'float32')
        self.patch_embedding.weight = self.load_pnnx_bin_as_parameter(archive, 'patch_embedding.weight', (1152,3,16,16), 'float32')
        self.layers_0_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.0.input_layernorm.bias', (1152), 'float32')
        self.layers_0_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.0.input_layernorm.weight', (1152), 'float32')
        self.attention_0.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_0.in_proj_bias', (3456), 'float32')
        self.attention_0.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_0.in_proj_weight', (3456,1152), 'float32')
        self.attention_0.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_0.out_proj.bias', (1152), 'float32')
        self.attention_0.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_0.out_proj.weight', (1152,1152), 'float32')
        self.layers_0_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.0.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_0_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.0.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_0_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.0.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_0_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.0.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_0_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.0.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_0_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.0.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_1_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.1.input_layernorm.bias', (1152), 'float32')
        self.layers_1_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.1.input_layernorm.weight', (1152), 'float32')
        self.attention_1.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_1.in_proj_bias', (3456), 'float32')
        self.attention_1.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_1.in_proj_weight', (3456,1152), 'float32')
        self.attention_1.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_1.out_proj.bias', (1152), 'float32')
        self.attention_1.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_1.out_proj.weight', (1152,1152), 'float32')
        self.layers_1_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.1.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_1_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.1.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_1_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.1.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_1_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.1.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_1_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.1.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_1_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.1.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_2_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.2.input_layernorm.bias', (1152), 'float32')
        self.layers_2_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.2.input_layernorm.weight', (1152), 'float32')
        self.attention_2.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_2.in_proj_bias', (3456), 'float32')
        self.attention_2.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_2.in_proj_weight', (3456,1152), 'float32')
        self.attention_2.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_2.out_proj.bias', (1152), 'float32')
        self.attention_2.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_2.out_proj.weight', (1152,1152), 'float32')
        self.layers_2_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.2.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_2_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.2.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_2_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.2.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_2_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.2.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_2_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.2.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_2_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.2.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_3_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.3.input_layernorm.bias', (1152), 'float32')
        self.layers_3_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.3.input_layernorm.weight', (1152), 'float32')
        self.attention_3.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_3.in_proj_bias', (3456), 'float32')
        self.attention_3.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_3.in_proj_weight', (3456,1152), 'float32')
        self.attention_3.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_3.out_proj.bias', (1152), 'float32')
        self.attention_3.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_3.out_proj.weight', (1152,1152), 'float32')
        self.layers_3_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.3.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_3_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.3.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_3_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.3.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_3_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.3.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_3_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.3.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_3_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.3.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_4_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.4.input_layernorm.bias', (1152), 'float32')
        self.layers_4_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.4.input_layernorm.weight', (1152), 'float32')
        self.attention_4.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_4.in_proj_bias', (3456), 'float32')
        self.attention_4.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_4.in_proj_weight', (3456,1152), 'float32')
        self.attention_4.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_4.out_proj.bias', (1152), 'float32')
        self.attention_4.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_4.out_proj.weight', (1152,1152), 'float32')
        self.layers_4_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.4.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_4_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.4.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_4_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.4.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_4_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.4.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_4_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.4.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_4_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.4.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_5_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.5.input_layernorm.bias', (1152), 'float32')
        self.layers_5_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.5.input_layernorm.weight', (1152), 'float32')
        self.attention_5.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_5.in_proj_bias', (3456), 'float32')
        self.attention_5.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_5.in_proj_weight', (3456,1152), 'float32')
        self.attention_5.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_5.out_proj.bias', (1152), 'float32')
        self.attention_5.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_5.out_proj.weight', (1152,1152), 'float32')
        self.layers_5_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.5.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_5_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.5.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_5_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.5.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_5_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.5.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_5_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.5.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_5_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.5.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_6_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.6.input_layernorm.bias', (1152), 'float32')
        self.layers_6_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.6.input_layernorm.weight', (1152), 'float32')
        self.attention_6.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_6.in_proj_bias', (3456), 'float32')
        self.attention_6.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_6.in_proj_weight', (3456,1152), 'float32')
        self.attention_6.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_6.out_proj.bias', (1152), 'float32')
        self.attention_6.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_6.out_proj.weight', (1152,1152), 'float32')
        self.layers_6_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.6.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_6_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.6.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_6_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.6.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_6_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.6.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_6_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.6.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_6_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.6.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_7_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.7.input_layernorm.bias', (1152), 'float32')
        self.layers_7_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.7.input_layernorm.weight', (1152), 'float32')
        self.attention_7.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_7.in_proj_bias', (3456), 'float32')
        self.attention_7.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_7.in_proj_weight', (3456,1152), 'float32')
        self.attention_7.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_7.out_proj.bias', (1152), 'float32')
        self.attention_7.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_7.out_proj.weight', (1152,1152), 'float32')
        self.layers_7_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.7.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_7_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.7.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_7_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.7.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_7_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.7.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_7_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.7.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_7_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.7.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_8_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.8.input_layernorm.bias', (1152), 'float32')
        self.layers_8_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.8.input_layernorm.weight', (1152), 'float32')
        self.attention_8.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_8.in_proj_bias', (3456), 'float32')
        self.attention_8.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_8.in_proj_weight', (3456,1152), 'float32')
        self.attention_8.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_8.out_proj.bias', (1152), 'float32')
        self.attention_8.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_8.out_proj.weight', (1152,1152), 'float32')
        self.layers_8_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.8.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_8_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.8.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_8_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.8.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_8_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.8.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_8_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.8.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_8_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.8.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_9_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.9.input_layernorm.bias', (1152), 'float32')
        self.layers_9_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.9.input_layernorm.weight', (1152), 'float32')
        self.attention_9.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_9.in_proj_bias', (3456), 'float32')
        self.attention_9.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_9.in_proj_weight', (3456,1152), 'float32')
        self.attention_9.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_9.out_proj.bias', (1152), 'float32')
        self.attention_9.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_9.out_proj.weight', (1152,1152), 'float32')
        self.layers_9_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.9.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_9_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.9.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_9_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.9.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_9_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.9.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_9_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.9.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_9_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.9.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_10_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.10.input_layernorm.bias', (1152), 'float32')
        self.layers_10_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.10.input_layernorm.weight', (1152), 'float32')
        self.attention_10.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_10.in_proj_bias', (3456), 'float32')
        self.attention_10.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_10.in_proj_weight', (3456,1152), 'float32')
        self.attention_10.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_10.out_proj.bias', (1152), 'float32')
        self.attention_10.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_10.out_proj.weight', (1152,1152), 'float32')
        self.layers_10_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.10.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_10_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.10.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_10_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.10.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_10_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.10.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_10_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.10.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_10_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.10.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_11_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.11.input_layernorm.bias', (1152), 'float32')
        self.layers_11_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.11.input_layernorm.weight', (1152), 'float32')
        self.attention_11.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_11.in_proj_bias', (3456), 'float32')
        self.attention_11.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_11.in_proj_weight', (3456,1152), 'float32')
        self.attention_11.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_11.out_proj.bias', (1152), 'float32')
        self.attention_11.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_11.out_proj.weight', (1152,1152), 'float32')
        self.layers_11_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.11.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_11_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.11.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_11_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.11.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_11_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.11.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_11_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.11.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_11_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.11.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_12_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.12.input_layernorm.bias', (1152), 'float32')
        self.layers_12_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.12.input_layernorm.weight', (1152), 'float32')
        self.attention_12.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_12.in_proj_bias', (3456), 'float32')
        self.attention_12.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_12.in_proj_weight', (3456,1152), 'float32')
        self.attention_12.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_12.out_proj.bias', (1152), 'float32')
        self.attention_12.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_12.out_proj.weight', (1152,1152), 'float32')
        self.layers_12_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.12.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_12_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.12.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_12_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.12.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_12_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.12.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_12_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.12.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_12_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.12.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_13_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.13.input_layernorm.bias', (1152), 'float32')
        self.layers_13_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.13.input_layernorm.weight', (1152), 'float32')
        self.attention_13.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_13.in_proj_bias', (3456), 'float32')
        self.attention_13.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_13.in_proj_weight', (3456,1152), 'float32')
        self.attention_13.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_13.out_proj.bias', (1152), 'float32')
        self.attention_13.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_13.out_proj.weight', (1152,1152), 'float32')
        self.layers_13_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.13.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_13_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.13.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_13_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.13.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_13_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.13.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_13_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.13.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_13_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.13.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_14_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.14.input_layernorm.bias', (1152), 'float32')
        self.layers_14_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.14.input_layernorm.weight', (1152), 'float32')
        self.attention_14.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_14.in_proj_bias', (3456), 'float32')
        self.attention_14.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_14.in_proj_weight', (3456,1152), 'float32')
        self.attention_14.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_14.out_proj.bias', (1152), 'float32')
        self.attention_14.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_14.out_proj.weight', (1152,1152), 'float32')
        self.layers_14_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.14.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_14_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.14.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_14_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.14.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_14_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.14.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_14_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.14.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_14_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.14.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_15_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.15.input_layernorm.bias', (1152), 'float32')
        self.layers_15_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.15.input_layernorm.weight', (1152), 'float32')
        self.attention_15.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_15.in_proj_bias', (3456), 'float32')
        self.attention_15.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_15.in_proj_weight', (3456,1152), 'float32')
        self.attention_15.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_15.out_proj.bias', (1152), 'float32')
        self.attention_15.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_15.out_proj.weight', (1152,1152), 'float32')
        self.layers_15_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.15.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_15_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.15.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_15_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.15.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_15_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.15.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_15_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.15.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_15_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.15.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_16_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.16.input_layernorm.bias', (1152), 'float32')
        self.layers_16_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.16.input_layernorm.weight', (1152), 'float32')
        self.attention_16.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_16.in_proj_bias', (3456), 'float32')
        self.attention_16.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_16.in_proj_weight', (3456,1152), 'float32')
        self.attention_16.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_16.out_proj.bias', (1152), 'float32')
        self.attention_16.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_16.out_proj.weight', (1152,1152), 'float32')
        self.layers_16_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.16.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_16_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.16.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_16_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.16.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_16_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.16.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_16_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.16.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_16_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.16.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_17_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.17.input_layernorm.bias', (1152), 'float32')
        self.layers_17_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.17.input_layernorm.weight', (1152), 'float32')
        self.attention_17.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_17.in_proj_bias', (3456), 'float32')
        self.attention_17.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_17.in_proj_weight', (3456,1152), 'float32')
        self.attention_17.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_17.out_proj.bias', (1152), 'float32')
        self.attention_17.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_17.out_proj.weight', (1152,1152), 'float32')
        self.layers_17_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.17.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_17_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.17.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_17_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.17.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_17_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.17.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_17_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.17.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_17_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.17.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_18_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.18.input_layernorm.bias', (1152), 'float32')
        self.layers_18_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.18.input_layernorm.weight', (1152), 'float32')
        self.attention_18.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_18.in_proj_bias', (3456), 'float32')
        self.attention_18.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_18.in_proj_weight', (3456,1152), 'float32')
        self.attention_18.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_18.out_proj.bias', (1152), 'float32')
        self.attention_18.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_18.out_proj.weight', (1152,1152), 'float32')
        self.layers_18_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.18.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_18_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.18.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_18_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.18.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_18_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.18.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_18_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.18.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_18_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.18.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_19_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.19.input_layernorm.bias', (1152), 'float32')
        self.layers_19_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.19.input_layernorm.weight', (1152), 'float32')
        self.attention_19.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_19.in_proj_bias', (3456), 'float32')
        self.attention_19.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_19.in_proj_weight', (3456,1152), 'float32')
        self.attention_19.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_19.out_proj.bias', (1152), 'float32')
        self.attention_19.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_19.out_proj.weight', (1152,1152), 'float32')
        self.layers_19_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.19.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_19_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.19.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_19_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.19.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_19_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.19.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_19_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.19.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_19_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.19.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_20_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.20.input_layernorm.bias', (1152), 'float32')
        self.layers_20_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.20.input_layernorm.weight', (1152), 'float32')
        self.attention_20.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_20.in_proj_bias', (3456), 'float32')
        self.attention_20.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_20.in_proj_weight', (3456,1152), 'float32')
        self.attention_20.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_20.out_proj.bias', (1152), 'float32')
        self.attention_20.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_20.out_proj.weight', (1152,1152), 'float32')
        self.layers_20_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.20.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_20_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.20.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_20_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.20.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_20_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.20.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_20_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.20.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_20_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.20.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_21_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.21.input_layernorm.bias', (1152), 'float32')
        self.layers_21_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.21.input_layernorm.weight', (1152), 'float32')
        self.attention_21.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_21.in_proj_bias', (3456), 'float32')
        self.attention_21.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_21.in_proj_weight', (3456,1152), 'float32')
        self.attention_21.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_21.out_proj.bias', (1152), 'float32')
        self.attention_21.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_21.out_proj.weight', (1152,1152), 'float32')
        self.layers_21_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.21.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_21_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.21.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_21_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.21.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_21_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.21.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_21_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.21.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_21_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.21.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_22_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.22.input_layernorm.bias', (1152), 'float32')
        self.layers_22_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.22.input_layernorm.weight', (1152), 'float32')
        self.attention_22.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_22.in_proj_bias', (3456), 'float32')
        self.attention_22.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_22.in_proj_weight', (3456,1152), 'float32')
        self.attention_22.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_22.out_proj.bias', (1152), 'float32')
        self.attention_22.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_22.out_proj.weight', (1152,1152), 'float32')
        self.layers_22_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.22.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_22_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.22.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_22_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.22.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_22_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.22.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_22_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.22.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_22_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.22.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_23_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.23.input_layernorm.bias', (1152), 'float32')
        self.layers_23_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.23.input_layernorm.weight', (1152), 'float32')
        self.attention_23.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_23.in_proj_bias', (3456), 'float32')
        self.attention_23.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_23.in_proj_weight', (3456,1152), 'float32')
        self.attention_23.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_23.out_proj.bias', (1152), 'float32')
        self.attention_23.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_23.out_proj.weight', (1152,1152), 'float32')
        self.layers_23_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.23.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_23_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.23.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_23_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.23.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_23_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.23.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_23_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.23.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_23_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.23.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_24_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.24.input_layernorm.bias', (1152), 'float32')
        self.layers_24_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.24.input_layernorm.weight', (1152), 'float32')
        self.attention_24.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_24.in_proj_bias', (3456), 'float32')
        self.attention_24.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_24.in_proj_weight', (3456,1152), 'float32')
        self.attention_24.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_24.out_proj.bias', (1152), 'float32')
        self.attention_24.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_24.out_proj.weight', (1152,1152), 'float32')
        self.layers_24_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.24.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_24_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.24.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_24_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.24.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_24_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.24.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_24_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.24.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_24_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.24.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_25_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.25.input_layernorm.bias', (1152), 'float32')
        self.layers_25_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.25.input_layernorm.weight', (1152), 'float32')
        self.attention_25.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_25.in_proj_bias', (3456), 'float32')
        self.attention_25.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_25.in_proj_weight', (3456,1152), 'float32')
        self.attention_25.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_25.out_proj.bias', (1152), 'float32')
        self.attention_25.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_25.out_proj.weight', (1152,1152), 'float32')
        self.layers_25_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.25.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_25_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.25.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_25_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.25.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_25_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.25.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_25_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.25.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_25_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.25.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.layers_26_input_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.26.input_layernorm.bias', (1152), 'float32')
        self.layers_26_input_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.26.input_layernorm.weight', (1152), 'float32')
        self.attention_26.in_proj_bias = self.load_pnnx_bin_as_parameter(archive, 'attention_26.in_proj_bias', (3456), 'float32')
        self.attention_26.in_proj_weight = self.load_pnnx_bin_as_parameter(archive, 'attention_26.in_proj_weight', (3456,1152), 'float32')
        self.attention_26.out_proj.bias = self.load_pnnx_bin_as_parameter(archive, 'attention_26.out_proj.bias', (1152), 'float32')
        self.attention_26.out_proj.weight = self.load_pnnx_bin_as_parameter(archive, 'attention_26.out_proj.weight', (1152,1152), 'float32')
        self.layers_26_post_attention_layernorm.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.26.post_attention_layernorm.bias', (1152), 'float32')
        self.layers_26_post_attention_layernorm.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.26.post_attention_layernorm.weight', (1152), 'float32')
        self.layers_26_mlp_dense_h_to_4h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.26.mlp.dense_h_to_4h.bias', (4304), 'float32')
        self.layers_26_mlp_dense_h_to_4h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.26.mlp.dense_h_to_4h.weight', (4304,1152), 'float32')
        self.layers_26_mlp_dense_4h_to_h.bias = self.load_pnnx_bin_as_parameter(archive, 'layers.26.mlp.dense_4h_to_h.bias', (1152), 'float32')
        self.layers_26_mlp_dense_4h_to_h.weight = self.load_pnnx_bin_as_parameter(archive, 'layers.26.mlp.dense_4h_to_h.weight', (1152,4304), 'float32')
        self.rmsnorm_0.weight = self.load_pnnx_bin_as_parameter(archive, 'rmsnorm_0.weight', (1152), 'float32')
        self.perceive_proj_0.bias = self.load_pnnx_bin_as_parameter(archive, 'perceive.proj.0.bias', (2304), 'float32')
        self.perceive_proj_0.weight = self.load_pnnx_bin_as_parameter(archive, 'perceive.proj.0.weight', (2304,1152,2,2), 'float32')
        self.perceive_proj_2.bias = self.load_pnnx_bin_as_parameter(archive, 'perceive.proj.2.bias', (4608), 'float32')
        self.perceive_proj_2.weight = self.load_pnnx_bin_as_parameter(archive, 'perceive.proj.2.weight', (4608,2304,1,1), 'float32')
        self.perceive_mlp.bias = self.load_pnnx_bin_as_parameter(archive, 'perceive.mlp.bias', (1024), 'float32')
        self.perceive_mlp.weight = self.load_pnnx_bin_as_parameter(archive, 'perceive.mlp.weight', (1024,4608), 'float32')
        self.rmsnorm_1.weight = self.load_pnnx_bin_as_parameter(archive, 'rmsnorm_1.weight', (1024), 'float32')
        self.pnnx_fold_1787_data = self.load_pnnx_bin_as_parameter(archive, 'pnnx_fold_1787.data', (1,4608,1,1,), 'float32')
        self.pnnx_fold_begin_1_data = self.load_pnnx_bin_as_parameter(archive, 'pnnx_fold_begin.1.data', (1,1,1024,), 'float32')
        self.pnnx_fold_end_1_data = self.load_pnnx_bin_as_parameter(archive, 'pnnx_fold_end.1.data', (1,1,1024,), 'float32')
        archive.close()

    def load_pnnx_bin_as_parameter(self, archive, key, shape, dtype, requires_grad=True):
        return nn.Parameter(self.load_pnnx_bin_as_tensor(archive, key, shape, dtype), requires_grad)

    def load_pnnx_bin_as_tensor(self, archive, key, shape, dtype):
        fd, tmppath = tempfile.mkstemp()
        with os.fdopen(fd, 'wb') as tmpf, archive.open(key) as keyfile:
            tmpf.write(keyfile.read())
        m = np.memmap(tmppath, dtype=dtype, mode='r', shape=shape).copy()
        os.remove(tmppath)
        return torch.from_numpy(m)

    def forward(self, v_0, v_1):
        v_2 = self.patch_embedding(v_0)
        v_3 = (v_2 + v_1)
        v_4 = v_3.reshape(1, 1152, -1)
        v_5 = v_4.permute(dims=(0,2,1))
        v_6 = self.layers_0_input_layernorm(v_5)
        v_7, _ = self.attention_0(v_6, v_6, v_6, need_weights=False)
        v_8 = (v_5 + v_7)
        v_9 = self.layers_0_post_attention_layernorm(v_8)
        v_10 = self.layers_0_mlp_dense_h_to_4h(v_9)
        v_11 = F.gelu(v_10)
        v_12 = self.layers_0_mlp_dense_4h_to_h(v_11)
        v_13 = (v_8 + v_12)
        v_14 = self.layers_1_input_layernorm(v_13)
        v_15, _ = self.attention_1(v_14, v_14, v_14, need_weights=False)
        v_16 = (v_13 + v_15)
        v_17 = self.layers_1_post_attention_layernorm(v_16)
        v_18 = self.layers_1_mlp_dense_h_to_4h(v_17)
        v_19 = F.gelu(v_18)
        v_20 = self.layers_1_mlp_dense_4h_to_h(v_19)
        v_21 = (v_16 + v_20)
        v_22 = self.layers_2_input_layernorm(v_21)
        v_23, _ = self.attention_2(v_22, v_22, v_22, need_weights=False)
        v_24 = (v_21 + v_23)
        v_25 = self.layers_2_post_attention_layernorm(v_24)
        v_26 = self.layers_2_mlp_dense_h_to_4h(v_25)
        v_27 = F.gelu(v_26)
        v_28 = self.layers_2_mlp_dense_4h_to_h(v_27)
        v_29 = (v_24 + v_28)
        v_30 = self.layers_3_input_layernorm(v_29)
        v_31, _ = self.attention_3(v_30, v_30, v_30, need_weights=False)
        v_32 = (v_29 + v_31)
        v_33 = self.layers_3_post_attention_layernorm(v_32)
        v_34 = self.layers_3_mlp_dense_h_to_4h(v_33)
        v_35 = F.gelu(v_34)
        v_36 = self.layers_3_mlp_dense_4h_to_h(v_35)
        v_37 = (v_32 + v_36)
        v_38 = self.layers_4_input_layernorm(v_37)
        v_39, _ = self.attention_4(v_38, v_38, v_38, need_weights=False)
        v_40 = (v_37 + v_39)
        v_41 = self.layers_4_post_attention_layernorm(v_40)
        v_42 = self.layers_4_mlp_dense_h_to_4h(v_41)
        v_43 = F.gelu(v_42)
        v_44 = self.layers_4_mlp_dense_4h_to_h(v_43)
        v_45 = (v_40 + v_44)
        v_46 = self.layers_5_input_layernorm(v_45)
        v_47, _ = self.attention_5(v_46, v_46, v_46, need_weights=False)
        v_48 = (v_45 + v_47)
        v_49 = self.layers_5_post_attention_layernorm(v_48)
        v_50 = self.layers_5_mlp_dense_h_to_4h(v_49)
        v_51 = F.gelu(v_50)
        v_52 = self.layers_5_mlp_dense_4h_to_h(v_51)
        v_53 = (v_48 + v_52)
        v_54 = self.layers_6_input_layernorm(v_53)
        v_55, _ = self.attention_6(v_54, v_54, v_54, need_weights=False)
        v_56 = (v_53 + v_55)
        v_57 = self.layers_6_post_attention_layernorm(v_56)
        v_58 = self.layers_6_mlp_dense_h_to_4h(v_57)
        v_59 = F.gelu(v_58)
        v_60 = self.layers_6_mlp_dense_4h_to_h(v_59)
        v_61 = (v_56 + v_60)
        v_62 = self.layers_7_input_layernorm(v_61)
        v_63, _ = self.attention_7(v_62, v_62, v_62, need_weights=False)
        v_64 = (v_61 + v_63)
        v_65 = self.layers_7_post_attention_layernorm(v_64)
        v_66 = self.layers_7_mlp_dense_h_to_4h(v_65)
        v_67 = F.gelu(v_66)
        v_68 = self.layers_7_mlp_dense_4h_to_h(v_67)
        v_69 = (v_64 + v_68)
        v_70 = self.layers_8_input_layernorm(v_69)
        v_71, _ = self.attention_8(v_70, v_70, v_70, need_weights=False)
        v_72 = (v_69 + v_71)
        v_73 = self.layers_8_post_attention_layernorm(v_72)
        v_74 = self.layers_8_mlp_dense_h_to_4h(v_73)
        v_75 = F.gelu(v_74)
        v_76 = self.layers_8_mlp_dense_4h_to_h(v_75)
        v_77 = (v_72 + v_76)
        v_78 = self.layers_9_input_layernorm(v_77)
        v_79, _ = self.attention_9(v_78, v_78, v_78, need_weights=False)
        v_80 = (v_77 + v_79)
        v_81 = self.layers_9_post_attention_layernorm(v_80)
        v_82 = self.layers_9_mlp_dense_h_to_4h(v_81)
        v_83 = F.gelu(v_82)
        v_84 = self.layers_9_mlp_dense_4h_to_h(v_83)
        v_85 = (v_80 + v_84)
        v_86 = self.layers_10_input_layernorm(v_85)
        v_87, _ = self.attention_10(v_86, v_86, v_86, need_weights=False)
        v_88 = (v_85 + v_87)
        v_89 = self.layers_10_post_attention_layernorm(v_88)
        v_90 = self.layers_10_mlp_dense_h_to_4h(v_89)
        v_91 = F.gelu(v_90)
        v_92 = self.layers_10_mlp_dense_4h_to_h(v_91)
        v_93 = (v_88 + v_92)
        v_94 = self.layers_11_input_layernorm(v_93)
        v_95, _ = self.attention_11(v_94, v_94, v_94, need_weights=False)
        v_96 = (v_93 + v_95)
        v_97 = self.layers_11_post_attention_layernorm(v_96)
        v_98 = self.layers_11_mlp_dense_h_to_4h(v_97)
        v_99 = F.gelu(v_98)
        v_100 = self.layers_11_mlp_dense_4h_to_h(v_99)
        v_101 = (v_96 + v_100)
        v_102 = self.layers_12_input_layernorm(v_101)
        v_103, _ = self.attention_12(v_102, v_102, v_102, need_weights=False)
        v_104 = (v_101 + v_103)
        v_105 = self.layers_12_post_attention_layernorm(v_104)
        v_106 = self.layers_12_mlp_dense_h_to_4h(v_105)
        v_107 = F.gelu(v_106)
        v_108 = self.layers_12_mlp_dense_4h_to_h(v_107)
        v_109 = (v_104 + v_108)
        v_110 = self.layers_13_input_layernorm(v_109)
        v_111, _ = self.attention_13(v_110, v_110, v_110, need_weights=False)
        v_112 = (v_109 + v_111)
        v_113 = self.layers_13_post_attention_layernorm(v_112)
        v_114 = self.layers_13_mlp_dense_h_to_4h(v_113)
        v_115 = F.gelu(v_114)
        v_116 = self.layers_13_mlp_dense_4h_to_h(v_115)
        v_117 = (v_112 + v_116)
        v_118 = self.layers_14_input_layernorm(v_117)
        v_119, _ = self.attention_14(v_118, v_118, v_118, need_weights=False)
        v_120 = (v_117 + v_119)
        v_121 = self.layers_14_post_attention_layernorm(v_120)
        v_122 = self.layers_14_mlp_dense_h_to_4h(v_121)
        v_123 = F.gelu(v_122)
        v_124 = self.layers_14_mlp_dense_4h_to_h(v_123)
        v_125 = (v_120 + v_124)
        v_126 = self.layers_15_input_layernorm(v_125)
        v_127, _ = self.attention_15(v_126, v_126, v_126, need_weights=False)
        v_128 = (v_125 + v_127)
        v_129 = self.layers_15_post_attention_layernorm(v_128)
        v_130 = self.layers_15_mlp_dense_h_to_4h(v_129)
        v_131 = F.gelu(v_130)
        v_132 = self.layers_15_mlp_dense_4h_to_h(v_131)
        v_133 = (v_128 + v_132)
        v_134 = self.layers_16_input_layernorm(v_133)
        v_135, _ = self.attention_16(v_134, v_134, v_134, need_weights=False)
        v_136 = (v_133 + v_135)
        v_137 = self.layers_16_post_attention_layernorm(v_136)
        v_138 = self.layers_16_mlp_dense_h_to_4h(v_137)
        v_139 = F.gelu(v_138)
        v_140 = self.layers_16_mlp_dense_4h_to_h(v_139)
        v_141 = (v_136 + v_140)
        v_142 = self.layers_17_input_layernorm(v_141)
        v_143, _ = self.attention_17(v_142, v_142, v_142, need_weights=False)
        v_144 = (v_141 + v_143)
        v_145 = self.layers_17_post_attention_layernorm(v_144)
        v_146 = self.layers_17_mlp_dense_h_to_4h(v_145)
        v_147 = F.gelu(v_146)
        v_148 = self.layers_17_mlp_dense_4h_to_h(v_147)
        v_149 = (v_144 + v_148)
        v_150 = self.layers_18_input_layernorm(v_149)
        v_151, _ = self.attention_18(v_150, v_150, v_150, need_weights=False)
        v_152 = (v_149 + v_151)
        v_153 = self.layers_18_post_attention_layernorm(v_152)
        v_154 = self.layers_18_mlp_dense_h_to_4h(v_153)
        v_155 = F.gelu(v_154)
        v_156 = self.layers_18_mlp_dense_4h_to_h(v_155)
        v_157 = (v_152 + v_156)
        v_158 = self.layers_19_input_layernorm(v_157)
        v_159, _ = self.attention_19(v_158, v_158, v_158, need_weights=False)
        v_160 = (v_157 + v_159)
        v_161 = self.layers_19_post_attention_layernorm(v_160)
        v_162 = self.layers_19_mlp_dense_h_to_4h(v_161)
        v_163 = F.gelu(v_162)
        v_164 = self.layers_19_mlp_dense_4h_to_h(v_163)
        v_165 = (v_160 + v_164)
        v_166 = self.layers_20_input_layernorm(v_165)
        v_167, _ = self.attention_20(v_166, v_166, v_166, need_weights=False)
        v_168 = (v_165 + v_167)
        v_169 = self.layers_20_post_attention_layernorm(v_168)
        v_170 = self.layers_20_mlp_dense_h_to_4h(v_169)
        v_171 = F.gelu(v_170)
        v_172 = self.layers_20_mlp_dense_4h_to_h(v_171)
        v_173 = (v_168 + v_172)
        v_174 = self.layers_21_input_layernorm(v_173)
        v_175, _ = self.attention_21(v_174, v_174, v_174, need_weights=False)
        v_176 = (v_173 + v_175)
        v_177 = self.layers_21_post_attention_layernorm(v_176)
        v_178 = self.layers_21_mlp_dense_h_to_4h(v_177)
        v_179 = F.gelu(v_178)
        v_180 = self.layers_21_mlp_dense_4h_to_h(v_179)
        v_181 = (v_176 + v_180)
        v_182 = self.layers_22_input_layernorm(v_181)
        v_183, _ = self.attention_22(v_182, v_182, v_182, need_weights=False)
        v_184 = (v_181 + v_183)
        v_185 = self.layers_22_post_attention_layernorm(v_184)
        v_186 = self.layers_22_mlp_dense_h_to_4h(v_185)
        v_187 = F.gelu(v_186)
        v_188 = self.layers_22_mlp_dense_4h_to_h(v_187)
        v_189 = (v_184 + v_188)
        v_190 = self.layers_23_input_layernorm(v_189)
        v_191, _ = self.attention_23(v_190, v_190, v_190, need_weights=False)
        v_192 = (v_189 + v_191)
        v_193 = self.layers_23_post_attention_layernorm(v_192)
        v_194 = self.layers_23_mlp_dense_h_to_4h(v_193)
        v_195 = F.gelu(v_194)
        v_196 = self.layers_23_mlp_dense_4h_to_h(v_195)
        v_197 = (v_192 + v_196)
        v_198 = self.layers_24_input_layernorm(v_197)
        v_199, _ = self.attention_24(v_198, v_198, v_198, need_weights=False)
        v_200 = (v_197 + v_199)
        v_201 = self.layers_24_post_attention_layernorm(v_200)
        v_202 = self.layers_24_mlp_dense_h_to_4h(v_201)
        v_203 = F.gelu(v_202)
        v_204 = self.layers_24_mlp_dense_4h_to_h(v_203)
        v_205 = (v_200 + v_204)
        v_206 = self.layers_25_input_layernorm(v_205)
        v_207, _ = self.attention_25(v_206, v_206, v_206, need_weights=False)
        v_208 = (v_205 + v_207)
        v_209 = self.layers_25_post_attention_layernorm(v_208)
        v_210 = self.layers_25_mlp_dense_h_to_4h(v_209)
        v_211 = F.gelu(v_210)
        v_212 = self.layers_25_mlp_dense_4h_to_h(v_211)
        v_213 = (v_208 + v_212)
        v_214 = self.layers_26_input_layernorm(v_213)
        v_215, _ = self.attention_26(v_214, v_214, v_214, need_weights=False)
        v_216 = (v_213 + v_215)
        v_217 = self.layers_26_post_attention_layernorm(v_216)
        v_218 = self.layers_26_mlp_dense_h_to_4h(v_217)
        v_219 = F.gelu(v_218)
        v_220 = self.layers_26_mlp_dense_4h_to_h(v_219)
        v_221 = (v_216 + v_220)
        v_222 = self.rmsnorm_0(v_221)
        v_223 = v_222.permute(dims=(0,2,1))
        v_224 = [1, 1152, v_2.size(2), v_2.size(3)]
        v_225 = v_223.reshape(*v_224)
        v_226 = self.perceive_proj_0(v_225)
        v_227 = self.perceive_proj_1(v_226)
        v_228 = self.perceive_proj_2(v_227)
        v_229 = self.pnnx_fold_1787_data
        v_230 = v_228[:,:1,:,:1]
        v_231 = (v_229 + (v_230 * 0.0))
        v_232 = torch.cat((v_228, v_231), dim=3)
        v_233 = v_232.reshape(1, 4608, -1)
        v_234 = v_233.permute(dims=(0,2,1))
        v_235 = self.perceive_mlp(v_234)
        v_236 = self.pnnx_fold_begin_1_data
        v_237 = self.pnnx_fold_end_1_data
        v_238 = torch.cat((v_236, v_235, v_237), dim=1)
        v_239 = self.rmsnorm_1(v_238)
        return v_239

def export_torchscript():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 3, -1, -1, dtype=torch.float)
    v_1 = torch.rand(1, 1152, -1, -1, dtype=torch.float)

    mod = torch.jit.trace(net, (v_0, v_1))
    mod.save("D:\MySystem\share\SummerNcnn\pnnx\ncnn_ocr\scripts\ncnn\vision_encoder_pnnx.py.pt")

def export_onnx():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 3, -1, -1, dtype=torch.float)
    v_1 = torch.rand(1, 1152, -1, -1, dtype=torch.float)

    torch.onnx.export(net, (v_0, v_1), "D:\MySystem\share\SummerNcnn\pnnx\ncnn_ocr\scripts\ncnn\vision_encoder_pnnx.py.onnx", export_params=True, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK, opset_version=13, input_names=['in0', 'in1'], output_names=['out0'])

def export_pnnx():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 3, -1, -1, dtype=torch.float)
    v_1 = torch.rand(1, 1152, -1, -1, dtype=torch.float)

    import pnnx
    pnnx.export(net, "D:\MySystem\share\SummerNcnn\pnnx\ncnn_ocr\scripts\ncnn\vision_encoder_pnnx.py.pt", (v_0, v_1))

def export_ncnn():
    export_pnnx()

@torch.no_grad()
def test_inference():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 3, 384, 896, dtype=torch.float)
    v_1 = torch.rand(1, 1152, 24, 56, dtype=torch.float)

    return net(v_0, v_1)

if __name__ == "__main__":
    print(test_inference())
